# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98c7a4d30be4543d65559ab8a485e4784e4b9fc59819ba39b6da31a1d079bf73192498d92ee10bfc28d386f570a3367a3856b6cfb213db81d5ff3a51fe550b9c

test:
  secret_key_base: c40649b51d627c5707a018f6f021627ebf1b23b37615042db6f80ea37cc3cc01eb3c2b9272a6b7fc9181e036b53164bb7b76a2ddaed7d378156db802890d2d6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
